config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :recipes

  resources :users

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { medium: "22x20", thumb: "50x50" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes

  has_attached_file :avatar, styles: { medium: "20x20", thumb: "20x20" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password, :password_confirmation, :current_password, :avatar])
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @recipe= current_user.recipes.order("created_at DESC")

  end

  def new
    @button = "Crear"
    @recipe = current_user.recipes.build

  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end

  end

  def edit
    @button = "Modificar"
    @recipe = Recipe.find(params[:id])


  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "Receta modificada correctamente"
      redirect_to @recipe
    else
      render 'edit'
    end

  end

  def destroy

    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to action: "index", notice: "Receta eliminada correctamente"

  end

  def show
    @recipe = Recipe.find(params[:id])

  end

  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :elaboration, :user_id, :image)

  end

  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    redirect_to recipe_path, notice: "No esta autorizado a editar este articulo" if @recipe.nil?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  def show
    super
  end

  # DELETE /resource
  def destroy
    super
  end



  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  def update
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @user = current_user

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mt-5">
      <h1 class="display-3">Home</h1>
      <% provide(:titles, "Nombre pagina de recetas") %>


    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/header' %>
      <!-- <div class="alert alert-info">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> -->

        <ul>
          <% flash.each do |key,value|%>
          <li><%= value %></li>
          <% end %>
        </ul>
      </div>


    <div class="container">
      <%= yield %>
    </div>

  </body>

</html>

app/views/recipes/_edit.html.erb
<div class="container">
    <div class="row">
      <div class="col">
        <h2 class="display-4">Edit Recipe</h2>
          <%= form_for(@recipe) do |f| %>
          <div class="form-group row">
            <div class="col-12 mt-3">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>

            </div>

            <div class="col-12 mt-3">
                <%= f.label :ingredients %>
                <%= f.text_area :ingredients, class: 'form-control' %>

            </div>

            <div class="col-12 mt-3">
              <%= f.label :elaboration %>
              <%= f.text_area :elaboration, class: 'form-control' %>

            <div class="col-12 mt-3">
              <%= f.label :user_id %>
              <%= f.text_field :user_id, class: 'form-control' %><br>
            </div>

            <div class="field">
              <%= f.file_field :image %>
            </div>


            <%= f.submit "#{@boton} Crear", class: 'btn btn-primary' %>
          <% end %>
          </div>
      </div>
</div>

app/views/recipes/_form.html.erb
<div class="container">
    <div class="row mt-5">
      <div class="col">
        <h2 class="display-4">New Recipe</h2>
          <%= form_for(@recipe) do |f| %>
          <div class="form-group row">
            <div class="col-12 mt-2">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>

            </div>

            <div class="col-12 mt-3">
                <%= f.label :ingredients %>
                <%= f.text_area :ingredients, class: 'form-control' %>

            </div>

            <div class="col-12 mt-3">
              <%= f.label :elaboration %>
              <%= f.text_area :elaboration, class: 'form-control' %>

            <div class="col-12 mt-3">
              <%= f.label :user_id %>
              <%= f.text_field :user_id, class: 'form-control' %><br>
            </div>

            <div class="field my-3">
              <%= f.file_field :image %>
            </div>


            <%= f.submit "#{@boton} Crear", class: 'btn btn-info' %>
          <% end %>
          </div>
      </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'edit' %>

app/views/recipes/index.html.erb
<div class="container">
	<div class="row">
    <h1 class="text-center mt-5">Índice de Recetas</h1>
      <div class="MultiCarousel" data-items="1,3,4,4,4" data-slide="1" id="MultiCarousel"  data-interval="1000">
          <div class="MultiCarousel-inner">
            <% @recipe.each do |rec| %>
                <div class="item ">
                  <div class="pad15">
										
                      <h4 class="lead"><%= link_to rec.title, rec%></h4>
                      <p><%= rec.ingredients.truncate_words(15) %></p>
                      <p><%= rec.elaboration.truncate_words(15) %></p>
                  </div>
                </div>
            <% end %>
          </div>
          <button class="btn btn-primary leftLst"><</button>
          <button class="btn btn-primary rightLst">></button>
       </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="jumbotron recipeImage" style="background-image: url(<%= @recipe.image&.url(:medium) %>);">


  <div class="container">
      <h1 class="display-2 mb-3"><%= @recipe.title %></h1>
      <p class="lead mb-4"><%= @recipe.user_id %></p>

  </div>
</div>

  <div class="container">
    <div class="row d-flex">
      <div class="col">
        <div class="card">
            <div class="card-body">
              <h3 class="card-title display-4 mb-4"><%= @recipe.title %></h3>
                <div class="row mb-3 ml-2">
                  <h3 class="card-subtitle display-6 mb-4">Ingredients</h3>
                  <p class="card-text mb-4"><%= @recipe.ingredients %></p>
                </div>
                <div class="row mb-3 ml-2">
                  <h3 class="card-subtitle display-6 mb-4">Elaboration</h3>
                  <p class="card-text mb-4"><%= @recipe.elaboration %></p>
                </div>

                <div class="row justify-content-end mt-5">
                  <% if user_signed_in? %>
                    <%= link_to "Editar", edit_recipe_path(@recipe), class: 'btn btn-primary' %>
                    <%= link_to "Eliminar", @recipe,  method: :delete, data: {confirm: "¿Seguro que quieres eliminar la receta?"}, class: 'btn btn-success ml-3' %>
                  <% end %>

                </div>
            </div>
          </div>">

        </div>

    </div>

  </div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <%= link_to 'Home', root_path, class: 'homeButton' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav fm-nav navbar-right">
      <% if !user_signed_in? %>
        <%= link_to 'Iniciar Sesión', new_user_session_path %>
      <% else %>
        <%= link_to 'Nueva Receta', new_recipe_path %>
        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
        <%= link_to 'Editar Perfil', edit_user_registration_path %>
        <%= link_to "Profile", users_path %>
        <%= link_to "Index", recipes_path %>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 mt-5">
      <%= @user.name %>
    </div>
    <div class="col-12 mt-5">
      <%= @user.id %>
    </div>
    <div class="col-12 mt-5">
      <%= image_tag @user.avatar.url(:medium), class: "thumbnail avatarImage"  %>
    </div>



  </div>

</div>